enum JobStatus {
  PENDING = "PENDING",
  APPLICATION = "APPLICATION",
  ACTIVE = "ACTIVE",
  CANCELLED = "CANCELLED",
  COMPLETED = "COMPLETED",
  DISPUTED = "DISPUTED",
}

export default JobStatus;
